### ISSUE TITLE
Remove unnecessary var() declarations in functions

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#10]
Many functions have unnecessary `var()` style declarations in the beginning, for example

https://github.com/skycoin/exchange-api/blob/master/db/orderbooktracker.go#L37-L40
```go
	var (
		r   exchange.MarketRecord
		err error
	)
```

These should be replaced with `:=` assignment where possible

**Comment by briancaine** [comment]
So I went through the source (partially) and replaced var declarations with := initializations when possible. If the variable is immediately passed as a pointer to something, I just left the var intact.

https://github.com/briancaine/skycoin-exchange-api/commit/17187620cf44dc214e9930da2787748122596971

That's my progress above.

However, with the example you gave just now, that function doesn't seem like it can (easily) be rewritten to use `:=`. Am I missing something?

**Comment by gz-c** [comment]
For empty-value initialization, just do `var foo`, don't wrap it in extra braces when its inside of a function.

Also, this isn't C, we don't declare all variables ahead of time.  Declare them only when needed.

Also do not use "new()", especially not for builtin types like `string`, `float64`.

In the example I gave above, we already rewrote it to remove the `var()` declarations.

**Comment by briancaine** [comment]
Gotcha. How is my progress thus far? Did I miss anything?

**Comment by gz-c** [comment]
These are all unnecessary:

https://github.com/briancaine/skycoin-exchange-api/commit/17187620cf44dc214e9930da2787748122596971#diff-1a47f69e80fde8a6369df62216051897R12

other than that looks ok
