### ISSUE TITLE
Fix api response JSON structs 

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#19]
These have the API response JSON structs defined inside of a function:

https://github.com/skycoin/exchange-api/blob/master/exchange/c2cx.com/responses.go
https://github.com/skycoin/exchange-api/blob/master/exchange/cryptopia.co.nz/responses.go

They should be at the top level.  And the structs can implement a function that returns Balances()

`Balances()` should return `map[string]decimal.Decimal`.

The JSON fields that are float64 should be `decimal.Decimal` (https://godoc.org/github.com/shopspring/decimal)

In C2CX's case, "frozen" values must be subtracted from "balance" to get the spendable values. `Balances()` should return spendable values.  You must use the decimal library to parse and perform calculations with floating point values.

**Comment by briancaine** [comment]
https://github.com/briancaine/skycoin-exchange-api/blob/9af2848a160cf463971a4a602a47865f68607162/exchange/c2cx.com/responses.go#L19

How does this look?

**Comment by gz-c** [comment]
@briancaine its moved to the top level but it is still parsing to float64 and not to decimal.Decimal

**Comment by briancaine** [comment]
https://github.com/briancaine/skycoin-exchange-api/blob/06abd27e60531e6a00cb3e06817d086229addc54/exchange/cryptopia.co.nz/responses.go

So, two questions:
1. I needed a small utility function to turn decimal.Decimal's into float64's for the purposes of string formatting on [line 43](https://github.com/briancaine/skycoin-exchange-api/blob/06abd27e60531e6a00cb3e06817d086229addc54/exchange/cryptopia.co.nz/responses.go#L43).

    But that doesn't look very Go-esque though. Should I put it at toplevel?

2. [`cryptopia.Order`s](https://github.com/briancaine/skycoin-exchange-api/blob/06abd27e60531e6a00cb3e06817d086229addc54/exchange/cryptopia.co.nz/cryptopia.go#L238) use float64's too. Should I change that struct as well? (And whatever code touches that struct.)

**Comment by gz-c** [comment]
1. Use this https://godoc.org/github.com/shopspring/decimal#Decimal.String
2. Yes

**Comment by briancaine** [comment]
Ok, so, I rewrote [some more code](https://github.com/briancaine/skycoin-exchange-api/tree/fix-api-response-json-structs) to use decimal.Decimals instead of float64s.

I'm not really sure which parts of the code to rewrite though. Should I be removing all usages of floats from the whole repo?

**Comment by gz-c** [comment]
yes, any value that is monetary related must never be represented as a float, you cannot accurately convert between float and decimal.Decimal
