### ISSUE TITLE
Add travisci build badge to readme

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#27]
Add this badge:

[![Build Status](https://travis-ci.org/skycoin/exchange-api.svg?branch=master)](https://travis-ci.org/skycoin/exchange-api)

src: 
`[![Build Status](https://travis-ci.org/skycoin/exchange-api.svg?branch=master)](https://travis-ci.org/skycoin/exchange-api)`

**Comment by briancaine** [comment]
Done.

**Comment by gz-c** [comment]
You can write "Fixes #xxx" in the PR to have it auto close
