### ISSUE TITLE
Fix travis build errors

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#29]
Errors seen here:

https://travis-ci.org/skycoin/exchange-api/builds/335458623

```
gometalinter --deadline=2m --disable-all -E goimports -E unparam --tests --vendor ./...
cli/c2cx.go:1::warning: file is not goimported (goimports)
cli/create.go:1::warning: file is not goimported (goimports)
cli/render.go:1::warning: file is not goimported (goimports)
rpc/client.go:1::warning: file is not goimported (goimports)
rpc/utils.go:1::warning: file is not goimported (goimports)
exchange/c2cx.com/api.go:28:17:warning: parameter method always receives "getorderbook" (unparam)
```

Need to run `make format` to fix the `goimports` warnings.

`exchange/c2cx.com/api.go:28:17:warning: parameter method always receives "getorderbook"`
This line can be marked with `// nolint: unparam`

**Comment by briancaine** [comment]
https://github.com/briancaine/skycoin-exchange-api/tree/pass-tests

I found and fixed an issue with argument names.

However, most of the issues are with out-of-date API keys. We might consider making a couple of dummy accounts (one c2cx and one cryptopia) and [adding their encryption keys as a encrypted variables in travis](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

I checked the cryptopia errors, and they mostly seem to be a result of the missing keys.

I'm not able to make a c2cx API key (waiting to hear back from customer service on that one), so I don't know about that.

**Comment by gz-c** [comment]
we can't keep api keys in the public code. hide the live tests behind a feature flag or move to a separate package and skip tests for them in travis

**Comment by briancaine** [comment]
That's why I suggested adding them as encrypted variables in travis. I think that feature is specifically for API keys and passwords and things like that.

What I'll do, is move the test API keys to some env variable, and have it skip the tests if the env variables are unset.

**Comment by gz-c** [comment]
@briancaine ok that will work, we can configure travis with the encrypted variables through the shell, and skip those tests if they are not set

**Comment by briancaine** [comment]
The cryptopia tests are kind of confusing. Some of them simply don't make sense. (ie I[ commented one test out because it was testing to fetch order ID #1, which is unlikely to pass](https://github.com/briancaine/skycoin-exchange-api/commit/58abacb2a3e7c269f7f28eeda7e78a4942b601b6#diff-710710801f7b38e66a0700c2e25747e8L113))

I managed to get the rest of them to pass, but it's still a mess. Should I take some time and refactor the tests? How important this code overall?

I don't have an API key, for c2cx, so I can't test that yet.

**Comment by briancaine** [comment]
Oh, also, I added build tags to the integration tests. There's a tag for redis, c2cx and cryptopia.

**Comment by gz-c** [comment]
disable cryptopia tests

**Comment by briancaine** [comment]
Ok, we can just omit the API key and they won't run.

Just waiting for C2CX support to get back to me about the API key. I emailed them 2 days ago and they said they were working on it.
