### ISSUE TITLE
Ability to get spendable balance from c2cx

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#38]
Need a function to get the balance of an account on C2CX.

https://api.c2cx.com/
https://api.c2cx.com/v1/getbalance

```json
{
   "code":200,
   "message":"success",
   "data":{
      "balance":{
         "btc":21.02938304,
         "cny":107132.59597700,
         "eth":10.46997897,
         "etc":109.34651160,
         "sky":501.09096000
      },
      "frozen":{
         "btc":0.11800000,
         "cny":1000.00000000,
         "eth":9.46800000,
         "etc":24.91900000,
         "sky":0.00000000
      }
   }
}  
```

The "frozen" values must be subtracted from the "balance" values to obtain the spendable balance

**Comment by briancaine** [comment]
1. Do we want the balance in a numeric form? Or just for human display?

2. And for this (and the other issues like this), do you mind if I change the interfaces a bit? Like, do we have to maintain backwards compatibility with other code?

    For example, I'd want to rename the existing exchange.Client.GetBalance to maybe GetBalanceDisplay, and reserve GetBalance for actual numeric values.

**Comment by gz-c** [comment]
1. All monetary values must be in decimal.Decimal
2. Nothing uses this library yet, you can do whatever to the API
2b. GetBalanceDisplay isn't necessary, the decimal.Decimal type has formatters itself

**Comment by gz-c** [comment]
Implemented here:
https://github.com/briancaine/skycoin-exchange-api/blob/03bbd41d42d7b8c85afd09d6719f0626f9a148b0/exchange/c2cx.com/responses.go#L31

**Comment by gz-c** [comment]
Leaving it open until it is all gathered into a document. All of these issues related to methods are for methods we need for OTC passthrough and I do not want to go searching for them again
