### ISSUE TITLE
Ability to check order status with C2CX

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#42]

**Comment by stgleb** [comment]
I'll take this one, may take ~1 day

**Comment by gz-c** [comment]
This may be complete, if it is completed, make sure it is documented and provide an example.  Godoc supports examples, you can write an example that way (google how to add examples to godoc).  Link to instructions/documentation in the issue so I can check it

**Comment by stgleb** [comment]
@gz-c thanks, this looks implemented. I'll update docs about that

**Comment by stgleb** [comment]
This one is already implemented https://godoc.org/github.com/skycoin/exchange-api/exchange/c2cx.com#Client.OrderStatus
