### ISSUE TITLE
C2CX CLI tool

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#57]
Implement a new `cmd/c2cx/c2cx.go` CLI tool.

Use
https://github.com/spf13/cobra for the CLI 
and 
https://github.com/spf13/viper to load the config file

Load API keys from a config file `~/.exchangectl/config.toml`.  The keys should be in a section like:

```toml
[c2cx]
key = "xxxxx"
secret = "yyyyy"
```

For each public method on `c2cx.Client`, create a CLI command wrapper.

Example:

For

```go
func (c *Client) GetOrderbook(symbol TradePair) (*Orderbook, error)
```

create a command

`go run cmd/c2cx/c2cx.go get_orderbook <trade_pair>`

List of public methods:

https://godoc.org/github.com/skycoin/exchange-api/exchange/c2cx#Client

**Comment by briancaine** [comment]
I'll begin on this after #63 is merged.

**Comment by Vavilen** [comment]
Public methods:
- [x] CancelAll
- [x] CancelMultiple
- [x] CancelOrder
- [x] GetBalanceSummary
- [x] GetOrderByStatus
- [x] GetOrderByStatusPaged
- [x] GetOrderInfo
- [x] GetOrderInfoAll
- [x] GetOrderbook
- [x]  LimitBuy
- [x] LimitSell
- [x] MarketBuy
- [x] MarketSell

**Comment by Vavilen** [comment]
@gz-c , what should the cli tool return? For a successful result, I can print to stdout marshaled into JSON structure. For error response, I can print to stdout just an error message or wrap it in some error JSON message.

**Comment by gz-c** [comment]
No error: Print the JSON with MarshalIndent to be readable, to stdout. exit code 0

Error:  Print err.Error() to stderr, exit code 1

**Comment by Vavilen** [comment]
Public methods description:
- [x] CancelAll
- [x] CancelMultiple
- [x] CancelOrder
- [x] GetBalanceSummary
- [x] GetOrderByStatus
- [x] GetOrderByStatusPaged
- [x] GetOrderInfo
- [x] GetOrderInfoAll
- [x] GetOrderbook
- [x]  LimitBuy
- [x] LimitSell
- [x] MarketBuy
- [x] MarketSell

**Comment by Vavilen** [comment]
PR #80
