### ISSUE TITLE
Add exchange-specific price and volume decimal restrictions

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#60]
E.g.

For a BTC_SKY pair order on c2cx, 

Minimum volume: 1 SKY
Volume decimal precision: 2 (e.g. 1.01 SKY)
Price decimal precision: 5 (e.g. 0.00101 BTC)

These configured variables should be queryable by the name of the pair, in this case BTC_SKY

**Comment by briancaine** [comment]
For C2CX, this information is a constant, right?

**Comment by gz-c** [comment]
I've begun it in `TradePairRulesTable`

**Comment by gz-c** [comment]
The restrictions are undocumented

**Comment by gz-c** [comment]
More restrictions can be added as needed. They are not documented by c2cx.  The restrictions for a tradepair can be inferred by looking at the `[price, volume]` values in the orderbook API response
