### ISSUE TITLE
Use dep to vendor dependencies

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#7]
Dependencies are vendored (at least partially) already in the `vendor` folder, but a `Gopkg.toml` and `Gopkg.lock` file are missing, which are used by `dep`

**Comment by briancaine** [comment]
Actually, I just noticed that those vendored dependencies were setup as git submodules.

https://github.com/skycoin/exchange-api/issues/14

Do we still want to go through [this PR](https://github.com/skycoin/exchange-api/pull/16)?

**Comment by gz-c** [comment]
The vendoring is pulling in git submodules? haven't seen that before

**Comment by gz-c** [comment]
https://github.com/skycoin/skycoin#dependency-management
