### ISSUE TITLE
C2CX API integration tests

### ISSUE THREAD

**Issue by gz-c** [uberfurrer/tradebot#81]

**Comment by Vavilen** [comment]
Completed test cases
- [x] get_orderbook
- [x] get_balance_summary
- [x] create_order
- [x] get_order_info
- [x] get_order_info_all
- [x] cancel_order
- [x] cancel_multiple
- [x] cancel_all
- [x] limit_buy
- [x] limit_sell
- [ ] market_buy
- [ ] market_sell
- [x] get_ticker
- [x] get_order_by_status
- [x] get_order_by_status_paged
